### ISSUE TITLE
Overriding app_path and web_path defaults doesn't seem to take effect

### ISSUE THREAD

**Issue by billydavies** [capistrano/symfony#34]
My Symfony2 project root is in a sub-directory (i.e. the structure is '/htdocs/app, /htdocs/bin' etc).  I do this to avoid mixing my Vagrant files in with Symfony files.   I overrode the app_path and web_path defaults in deploy.rb using:

set :app_path, 'htdocs/app'
set :web_path, 'htdocs/web'

but when I run 'cap staging deploy' the defaults of 'app' and 'web are still in effect.  I'm not a Ruby developer so debugging where this is falling down is beyond me I'm afraid! Thanks in advance for any help given.

**Comment by Clindbergh** [comment]
I am trying to achieve the same, observing the same problem. 

Additonally composer fails because it expectes `composer.json` to be in the root directory. Even if `:app_path` and `:web_path` would work, I'd still expect the setup to fail. I'd think some setting like

`set :symfony_root_path, 'htdocs'` 

would be useful.

**Comment by Clindbergh** [comment]
oh and you're likely going to run into composer issues: capistrano/composer#37

**Comment by peterjmit** [comment]
@billydavies you need to override all of the setting (listed in README.md) that include `app_path` and `web_path`

i.e. in your `deploy.rb`

```ruby
set :app_path,              "htdocs/app"
set :web_path,              "htdocs/web"
set :log_path,              fetch(:app_path) + "/logs"
set :cache_path,            fetch(:app_path) + "/cache"
set :app_config_path,       fetch(:app_path) + "/config"
```
